import React,{useEffect,useRef} from 'react';
import {View,Text,StyleSheet,ScrollView,TouchableOpacity,Platform,Animated} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {ArrowLeft,ChevronRight,Sparkles} from 'lucide-react-native';
import {useIsFocused} from '@react-navigation/native';
import {GameExperience,useGameExperience,useMotionPermission,MotionReveal} from './GameMotion';

export const ink={navy:'#123449',muted:'#537080',paper:'#FFFDF6',cream:'#FFF3CE',teal:'#167D76',gold:'#FFD36B',orange:'#F49A4D',sky:'#E1F4F2',line:'#C6DDD8',white:'#FFFFFF'};
export function GameButton({label,onPress,secondary=false,disabled=false,compact=false,silent=false}:{label:string;onPress:()=>void;secondary?:boolean;disabled?:boolean;compact?:boolean;silent?:boolean}){
 const {motion,tap}=useGameExperience(), scale=useRef(new Animated.Value(1)).current;
 useEffect(()=>{if(!motion){scale.stopAnimation();scale.setValue(1);}return()=>scale.stopAnimation();},[motion,scale]);
 const press=(value:number)=>{if(motion){scale.stopAnimation();Animated.spring(scale,{toValue:value,speed:35,bounciness:7,useNativeDriver:Platform.OS!=='web',isInteraction:false}).start();}};
 return <Animated.View style={{transform:[{scale}]}}><TouchableOpacity accessibilityRole="button" accessibilityLabel={label} accessibilityState={{disabled}} disabled={disabled} onPressIn={()=>press(.97)} onPressOut={()=>press(1)} onPress={()=>{if(!silent)tap();onPress();}} activeOpacity={0.9} style={[k.button,secondary&&k.secondary,compact&&{paddingVertical:10,paddingHorizontal:10},disabled&&{opacity:0.5}]}><Text style={[k.buttonText,secondary&&{color:ink.navy},compact&&{fontSize:14,lineHeight:20}]}>{label}</Text>{!secondary?<ChevronRight size={19} color={ink.navy}/>:null}</TouchableOpacity></Animated.View>;
}
export function GameShell({children,title,subtitle,onBack,backLabel='Về danh sách bài',right,focusKey,wide=false,dock,onTap}:{children:React.ReactNode;title:string;subtitle?:string;onBack?:()=>void;backLabel?:string;right?:React.ReactNode;focusKey?:string;wide?:boolean;dock?:React.ReactNode;onTap?:()=>void}){
 const scroll=useRef<ScrollView>(null),heading=useRef<any>(null);
 const focused=useIsFocused(),motion=useMotionPermission(focused);
 useEffect(()=>{scroll.current?.scrollTo({y:0,animated:false});if(Platform.OS==='web'&&focusKey!==undefined){heading.current?.setAttribute?.('tabindex','-1');heading.current?.focus?.();}},[focusKey]);
 return <GameExperience.Provider value={{motion,tap:onTap||(()=>{})}}><SafeAreaView style={k.root}><ScrollView ref={scroll} keyboardShouldPersistTaps="handled" contentContainerStyle={k.scroll}><View style={[k.wrap,wide&&{maxWidth:1100}]}>
  <View style={k.top}><View style={{flexDirection:'row',alignItems:'center',gap:8,flexShrink:1}}><View style={k.logo}><Sparkles size={19} color={ink.navy}/></View><Text style={k.wordmark}>MILO<Text style={{color:'#7ACCC1'}}> / </Text>EXPLORER</Text></View>{right}</View>
  <View style={k.titleRow}>{onBack?<TouchableOpacity accessibilityRole="button" accessibilityLabel={backLabel} onPress={onBack} style={k.back}><ArrowLeft size={23} color={ink.white}/></TouchableOpacity>:null}<View style={{flex:1,gap:3}}>{subtitle?<Text style={k.eyebrow}>{subtitle}</Text>:null}<Text ref={heading} accessibilityRole="header" style={k.title}>{title}</Text></View></View>
  <MotionReveal trigger={focusKey} style={{gap:16}}>{children}</MotionReveal>
  <Text style={k.footer}>Một chút khám phá. Một điều để cùng thực hành.</Text>
 </View></ScrollView>{dock}</SafeAreaView></GameExperience.Provider>;
}
export const k=StyleSheet.create({root:{flex:1,backgroundColor:'#102E43'},scroll:{flexGrow:1,padding:16},wrap:{width:'100%',maxWidth:760,alignSelf:'center',gap:16,paddingBottom:20},top:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',justifyContent:'space-between',gap:12},logo:{backgroundColor:ink.gold,borderRadius:11,padding:7},wordmark:{flexShrink:1,fontSize:12,fontWeight:'900',letterSpacing:1.5,color:ink.white},titleRow:{flexDirection:'row',alignItems:'center',gap:12},title:{color:ink.white,fontSize:27,fontWeight:'900',letterSpacing:-0.6},eyebrow:{color:'#98D1CA',fontSize:12,fontWeight:'800',letterSpacing:1.3},back:{width:48,height:48,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:'#24475D'},footer:{textAlign:'center',fontSize:12,color:'#A3BFCC',paddingTop:8},card:{backgroundColor:ink.paper,borderRadius:25,padding:20,gap:14,borderWidth:1,borderColor:'#FFFFFF'},heading:{fontSize:22,lineHeight:29,fontWeight:'800',color:ink.navy},body:{fontSize:17,lineHeight:26,color:ink.navy},small:{fontSize:13,lineHeight:20,color:ink.muted},button:{minHeight:52,backgroundColor:ink.gold,borderRadius:16,borderWidth:1,borderBottomWidth:4,borderColor:'#DDA748',paddingVertical:13,paddingHorizontal:18,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:8},buttonText:{fontSize:16,lineHeight:23,fontWeight:'800',color:ink.navy,flexShrink:1,textAlign:'center'},secondary:{backgroundColor:'#EBF4F2',borderColor:'#C7DAD6',borderBottomWidth:2},pill:{backgroundColor:'#254D62',borderRadius:20,paddingHorizontal:12,paddingVertical:7},pillText:{color:'#FFE195',fontWeight:'800',fontSize:13},link:{minHeight:44,justifyContent:'center',paddingHorizontal:8},linkText:{fontSize:14,fontWeight:'700',color:'#CCE4EB',textDecorationLine:'underline'}});
