import React,{useMemo,useState} from 'react';
import {View,Text,StyleSheet,TouchableOpacity,Modal,ScrollView,useWindowDimensions} from 'react-native';
import Svg,{Path,Circle,Ellipse,Rect,Defs,LinearGradient,Stop,G} from 'react-native-svg';
import {ChevronDown,Compass,Lock,Flag,X,BookOpen} from 'lucide-react-native';
import {JourneyMapData,LessonSummary,ZoneSummary} from '../../types/curriculum';
import {CartoonIslandStageNode} from '../CartoonIslandStageNode';
import {GameButton,ink,k} from './GameKit';
import {MiloCompanion} from './MiloCompanion';
import {WorldAtmosphere,MotionReveal,useGameExperience} from './GameMotion';
import {SecretCaveEntrance,PurpleGemChest,WoodenFence} from '../BiomeDecorations';

function Scenery({height,width,zone}:{height:number;width:number;zone:number}){
 const sky=zone%3===2?['#B0A8EF','#DAD8F1','#9CB5D6']:zone%3===0?['#FFCB8A','#FBE9C9','#B9D59E']:['#86D9EA','#D4F1D8','#92CD96'];
 return <Svg width="100%" height={height} viewBox={`0 0 ${width} ${height}`}><Defs><LinearGradient id="journey-sky" x1="0" y1="0" x2="0" y2="1"><Stop offset="0" stopColor={sky[0]}/><Stop offset=".5" stopColor={sky[1]}/><Stop offset="1" stopColor={sky[2]}/></LinearGradient></Defs><Rect width={width} height={height} fill="url(#journey-sky)"/><Circle cx={width*.84} cy={75} r={58} fill="#FFF4BE"/><Circle cx={width*.84} cy={75} r={75} fill="#FFF4BE" opacity={.22}/><G transform={`scale(${width/600} 1)`}><Path d="M0 230 Q110 80 210 210 Q300 60 420 190 Q550 80 600 180 L600 370 L0 370Z" fill="#8DCBC1" opacity={.5}/><Path d={`M0 340 Q70 260 120 355 Q210 260 330 400 Q460 260 600 350 L600 ${height} L0 ${height}Z`} fill="#B0DCC1"/></G>
 {[{x:30,y:210},{x:535,y:330},{x:62,y:510},{x:510,y:680}].filter(p=>p.y<height).map((p,i)=><G key={i} transform={`translate(${p.x/600*width} ${p.y})`}><Ellipse cy={42} rx={24} ry={8} fill="#478B72" opacity={.18}/><Rect x={-4} y={0} width={8} height={40} rx={3} fill="#9B7550"/><Path d="M0 -48 C-30 -30 -37 2 -20 11 C-35 31 10 37 25 14 C43 0 24 -33 0 -48Z" fill={i%2?'#428F72':'#6CAF80'}/><Path d="M-9 -26 Q-23 -7 -16 8" stroke="#9FD29D" strokeWidth={6} strokeLinecap="round" fill="none"/></G>)}
 {[{x:70,y:70},{x:390,y:145}].map((p,i)=><G key={i} transform={`translate(${p.x/600*width} ${p.y})`} fill="#F6FFFA" opacity={.7}><Ellipse rx={48} ry={12}/><Ellipse cx={-12} cy={-10} rx={24} ry={18}/><Ellipse cx={17} cy={-8} rx={19} ry={14}/></G>)}</Svg>;
}
type Target={lesson:LessonSummary;zone:ZoneSummary};
export function JourneyMap({data,search,open,active=true,onCollection}:{data:JourneyMapData;search:string;open:(id:string,title:string,zone:string)=>void;active?:boolean;onCollection?:()=>void}){
 const {width,fontScale}=useWindowDimensions();
 const {tap,motion}=useGameExperience();
 const [canvasWidth,setCanvasWidth]=useState(Math.min(width-36,724));
 const [nodeHeights,setNodeHeights]=useState<Record<string,number>>({});
 const [chosen,setChosen]=useState<string|null>(null),[chapterMenu,setChapterMenu]=useState(false),[target,setTarget]=useState<Target|null>(null);
 const firstReady=data.zones.find(z=>z.stages.some(s=>s.lessons.some(l=>l.status==='UNLOCKED'||l.status==='IN_PROGRESS')));
 const zone=data.zones.find(z=>z.id===chosen)||firstReady||data.zones[0];
 const items=useMemo(()=>data.zones.flatMap(z=>z.stages.flatMap(st=>st.lessons.filter(l=>l.isAvailable!==false).map(lesson=>({lesson,zone:z})))),[data]);
 if(!zone)return null;
 const lessons=items.filter(t=>t.zone.id===zone.id),spacing=190*Math.max(1,Math.min(fontScale,2));
 let cursor=74;
 const positions=lessons.map((item,i)=>{const p={x:[.39,.69,.31,.64][i%4],y:cursor};cursor+=Math.max(spacing,(nodeHeights[item.lesson.id]||140)+48);return p;});
 const height=Math.max(530,cursor+50);
 const path=positions.map((p,i)=>i?`C ${positions[i-1].x*1000} ${positions[i-1].y+spacing*.6}, ${p.x*1000} ${p.y-spacing*.6}, ${p.x*1000} ${p.y}`:`M ${p.x*1000} ${p.y}`).join(' ');
 const found=search.trim()?items.filter(t=>(t.lesson.title+' '+t.lesson.description+' '+t.zone.title).toLocaleLowerCase('vi-VN').includes(search.trim().toLocaleLowerCase('vi-VN'))):[];
 const completed=lessons.filter(t=>t.lesson.status==='COMPLETED').length;
 return <View style={{gap:12}}>
  <TouchableOpacity accessibilityRole="button" accessibilityLabel="Đổi chủ đề" aria-expanded={chapterMenu} accessibilityState={{expanded:chapterMenu}} onPress={()=>setChapterMenu(!chapterMenu)} style={g.chapter}><View style={g.chapterIcon}><Compass size={23} color={ink.teal}/></View><View style={{flex:1}}><Text style={g.chapterEyebrow}>CHƯƠNG {zone.zoneNumber.toString().padStart(2,'0')}</Text><Text style={g.chapterName}>{zone.title}</Text></View><ChevronDown size={22} color={ink.navy}/></TouchableOpacity>
  {chapterMenu?<View style={g.menu}>{data.zones.map(z=><TouchableOpacity key={z.id} accessibilityRole="button" accessibilityLabel={'Chủ đề: '+z.title} aria-pressed={z.id===zone.id} accessibilityState={{selected:z.id===zone.id}} onPress={()=>{setChosen(z.id);setChapterMenu(false);}} style={g.menuItem}><Text style={[k.body,{flex:1}]}>{z.title}</Text>{!z.isUnlocked?<Lock size={17} color={ink.muted}/>:null}</TouchableOpacity>)}</View>:null}
  {search.trim()?<View style={g.menu}><Text style={k.heading}>{found.length} bài tìm thấy</Text>{found.map(t=><TouchableOpacity key={t.lesson.id} accessibilityRole="button" onPress={()=>{tap();setTarget(t);}} style={g.menuItem}><BookOpen size={20} color={ink.teal}/><View style={{flex:1}}><Text style={g.chapterName}>{t.lesson.title}</Text><Text style={k.small}>{t.zone.title}</Text></View></TouchableOpacity>)}{!found.length?<Text style={k.body}>Thử tên bài hoặc chủ đề khác nhé.</Text>:null}</View>:<View style={g.map}>
   <View style={g.mapCaption}><View style={{flexDirection:'row',gap:7,alignItems:'center'}}><Flag size={16} color={ink.teal}/><Text style={g.mapCaptionText}>{completed}/{lessons.length} chặng hoàn thành</Text></View><Text style={g.mapCaptionText}>Chạm đảo để khám phá</Text></View>
   <View onLayout={e=>setCanvasWidth(e.nativeEvent.layout.width)} style={{height,position:'relative'}}><View pointerEvents="none" style={StyleSheet.absoluteFill}><Scenery height={height} width={canvasWidth} zone={zone.zoneNumber}/><WorldAtmosphere active={active&&!target} width={canvasWidth}/><View pointerEvents="none" style={{position:'absolute',left:4,top:210}}><SecretCaveEntrance width={82} height={72}/></View><View pointerEvents="none" style={{position:'absolute',right:12,top:height-105}}><WoodenFence width={65} height={39}/></View></View><View pointerEvents="none" style={StyleSheet.absoluteFill}><Svg width="100%" height={height} viewBox={`0 0 1000 ${height}`} preserveAspectRatio="none"><Path d={path} fill="none" stroke="#B99954" strokeWidth={30}/><Path d={path} fill="none" stroke="#FFF2B7" strokeWidth={23}/><Path d={path} fill="none" stroke="#E8C86E" strokeWidth={3} strokeDasharray="9 12"/></Svg></View>
    {lessons.map((t,i)=>{const {lesson}=t,p=positions[i],unlocked=zone.isUnlocked&&lesson.status!=='LOCKED',current=lesson.status==='UNLOCKED'||lesson.status==='IN_PROGRESS';return <View key={lesson.id} onLayout={e=>{const h=e.nativeEvent.layout.height;setNodeHeights(previous=>Math.abs((previous[lesson.id]||0)-h)<1?previous:{...previous,[lesson.id]:h});}} style={[g.node,{left:`${p.x*100}%`,top:p.y-42}]}>
     {current?<View style={g.you}><Text style={g.youText}>CHẶNG CỦA CON</Text></View>:null}{current&&width>340?<View style={g.companion}><MiloCompanion size={100} state="idle" active={active&&!target}/></View>:null}
     <CartoonIslandStageNode stage={{id:lesson.id,stageNumber:i+1,title:lesson.title,description:lesson.description,lessons:[lesson]}} isUnlocked={unlocked} isCompleted={lesson.status==='COMPLETED'} isBossStage={false} onPress={()=>setTarget(t)}/>
     <TouchableOpacity accessibilityRole="button" accessibilityLabel={'Chi tiết: '+lesson.title} onPress={()=>setTarget(t)} style={[g.label,current&&g.currentLabel]}><Text style={[g.labelText,current&&{color:ink.white}]}>{lesson.title}</Text><Text style={[g.nodeProgress,current&&{color:'#C8EDE5'}]}>{lesson.completedCheckpointIds?.length||0}/{lesson.checkpointIds?.length||0} phần đã đạt</Text></TouchableOpacity>
    </View>;})}<View style={[g.destination,{top:height-60}]}><Flag size={23} color={ink.teal}/><Text style={g.mapCaptionText}>Từng bước, cùng lớn lên</Text></View>
   </View>
  </View>}
  {onCollection?<TouchableOpacity accessibilityRole="button" accessibilityLabel="Mở rương hành trình" onPress={()=>{tap();onCollection();}} style={g.chest}><PurpleGemChest width={82} height={64}/><View style={{flex:1,gap:4}}><Text style={g.chapterName}>Rương hành trình</Text><Text style={k.small}>Xem dấu mốc và huy hiệu con đã đạt</Text></View><ChevronDown size={20} color={ink.teal}/></TouchableOpacity>:null}
  <Modal visible={!!target} transparent animationType={motion?'fade':'none'} onRequestClose={()=>setTarget(null)}><View style={g.scrim}><View accessibilityViewIsModal style={g.sheet}><ScrollView><MotionReveal trigger={target?.lesson.id} style={{gap:16}}><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><Text style={g.chapterEyebrow}>HỒ SƠ NHIỆM VỤ</Text><TouchableOpacity accessibilityRole="button" accessibilityLabel="Đóng nhiệm vụ" onPress={()=>setTarget(null)} style={g.close}><X size={22} color={ink.navy}/></TouchableOpacity></View><Text accessibilityRole="header" style={[k.heading,{fontSize:26}]}>{target?.lesson.title}</Text><Text style={k.body}>{target?.lesson.description}</Text><Text style={k.small}>Khoảng {target?.lesson.durationMinutes} phút · Có thể dừng và tiếp tục</Text>{target?.lesson.checkpointIds?.map((id,i)=><GameButton key={id} label={`${target.lesson.completedCheckpointIds?.includes(id)?'Ôn lại':'Học'} phần ${i+1}`} disabled={!target.zone.isUnlocked||target.lesson.status==='LOCKED'} onPress={()=>{open(id,target.lesson.title,target.zone.title);setTarget(null);}}/>)}{target&&(!target.zone.isUnlocked||target.lesson.status==='LOCKED')?<Text style={k.small}>Hoàn thành chặng trước để mở nhiệm vụ này.</Text>:null}</MotionReveal></ScrollView></View></View></Modal>
 </View>;
}
const g=StyleSheet.create({chest:{backgroundColor:'#FFF1C9',borderWidth:2,borderBottomWidth:5,borderColor:'#D9AD65',borderRadius:22,padding:14,flexDirection:'row',alignItems:'center',gap:12},chapter:{flexDirection:'row',gap:12,alignItems:'center',backgroundColor:ink.paper,padding:14,borderRadius:19},chapterIcon:{width:45,height:45,borderRadius:15,backgroundColor:'#DDF0E9',alignItems:'center',justifyContent:'center'},chapterEyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.5,color:ink.teal},chapterName:{fontSize:19,fontWeight:'800',color:ink.navy},menu:{backgroundColor:ink.paper,borderRadius:20,padding:16,gap:10},menuItem:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:12,minHeight:48,borderBottomWidth:1,borderColor:ink.line},map:{overflow:'hidden',borderRadius:25,borderWidth:2,borderColor:'#E5F9EF',backgroundColor:'#DDF3E6'},mapCaption:{paddingHorizontal:15,paddingVertical:12,flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',gap:6,backgroundColor:'#F0FAED'},mapCaptionText:{fontSize:12,color:'#3B6F63',fontWeight:'700'},node:{position:'absolute',width:156,marginLeft:-78,alignItems:'center'},label:{backgroundColor:'#FFFDF1',borderWidth:1,borderColor:'#BBD2B0',borderBottomWidth:3,borderRadius:14,paddingHorizontal:12,paddingVertical:8,minWidth:130,maxWidth:175,gap:2},currentLabel:{backgroundColor:ink.teal,borderColor:'#0E5954'},labelText:{fontSize:15,fontWeight:'800',textAlign:'center',color:ink.navy},nodeProgress:{fontSize:11,textAlign:'center',color:ink.muted},you:{backgroundColor:ink.gold,borderRadius:8,paddingHorizontal:8,paddingVertical:4,position:'absolute',top:-23},youText:{fontSize:9,fontWeight:'900',color:ink.navy,letterSpacing:.7},companion:{position:'absolute',top:-38,left:107},destination:{position:'absolute',left:0,right:0,alignItems:'center',gap:5},scrim:{flex:1,backgroundColor:'rgba(7,27,42,.68)',justifyContent:'center',alignItems:'center',padding:20},sheet:{width:'100%',maxWidth:460,maxHeight:'85%',backgroundColor:ink.paper,padding:24,borderRadius:28,borderWidth:2,borderColor:'#FFF1BD'},close:{height:44,width:44,alignItems:'center',justifyContent:'center',backgroundColor:'#EAF2EE',borderRadius:22}});
